name: kermut_no_m

use_mutation_kernel: false
use_global_kernel: true
embedding_type: ESM2
embedding_dim: 1280

use_zero_shot: true
zero_shot_method: ESM2
use_prior: true
noise_prior_scale: 0.1

gp_model:
  _target_: src.model.gp.ExactGPModelRBF

optim:
  n_steps: 150
  lr: 0.1