name: kermut

model:
  _target_: src.model.gp.ExactGPModelKermut

kernel_params:
  learnable_hellinger: true
  learnable_transform: true
  p_B: 15.0
  p_Q: 5.0
  theta: 0.5402
  gamma: 0.5402

conditional_probs_method: ProteinMPNN

tokenizer:
  _target_: src.model.utils.Tokenizer

optim:
  n_steps: 150
  lr: 0.1
  log_to_wandb: false