name: kermut_distance_no_blosum

use_mutation_kernel: true
use_global_kernel: false

mutation_kernel:
  model:
    _target_: src.model.kernel.Kermut_distance_no_blosum
  use_distances: true
  conditional_probs_method: ProteinMPNN
  tokenizer:
    _target_: src.model.model_utils.Tokenizer_oh_seq
    flatten: true
  kernel_params:
    h_scale: 0.5402
    h_lengthscale: 0.5402
    h_scale_2: 0.5402
    h_lengthscale_2: 0.5402

gp_model:
  _target_: src.model.gp.ExactGPKermut

use_zero_shot: true
zero_shot_method: TranceptEVE
use_prior: true
noise_prior_scale: 0.1

optim:
  n_steps: 150
  lr: 0.1