name: oh_mut_lin

model:
  _target_: src.model.gp.ExactGPModelLinear

kernel_params: { }

tokenizer:
  _target_: src.model.utils.Tokenizer_oh_mut

optim:
  n_steps: 150
  lr: 0.1
  log_to_wandb: false
