defaults:
  - gp: kermut
  - _self_
  - override hydra/job_logging: disabled  # Prevents creation of .log file from Hydra

dataset: ???
split_method: null
seed: 2024
progress_bar: false
overwrite: false
log_params: true
log_predictions: true
standardize: false


# Disables Hydra logging functionality
hydra:
  output_subdir: null
  job:
    chdir: false
  run:
    dir: .

