defaults:
  - experiment: ???
  - _self_
  - override hydra/job_logging: disabled  # Prevents creation of .log file from Hydra

encoding: ???  # either oh_mut or oh_seq
n_steps: 150
n_threads: 64

# Disables Hydra logging functionality
hydra:
  output_subdir: null
  job:
    chdir: false
  run:
    dir: .

