name: oh_mut_rbf

model:
  _target_: src.model.gp.ExactGPModelRBF

kernel_params: { }

tokenizer:
  _target_: src.model.model_utils.Tokenizer_oh_mut

optim:
  n_steps: 150
  lr: 0.1
  log_to_wandb: false
